### ISSUE TITLE
Incorrect Validation of Email address

### ISSUE THREAD

**Issue by Devunull** [JoshData/python-email-validator#108]
Found some issues with the Email validator not properly validating email addresses.
Email address:
`Something@hotco.uk`
hotco.uk doesn't exist (infact it's invalid `.uk` TLD)

Here is the example code I used to confirm this behaviour
```
import email_validator

email = "Something@hotco.uk"
maybe_valid= email_validator.validate_email(email, check_deliverability=True)
maybe_valid.normalized
```

I would expect this code to error as the domain `hotco.uk` cannot exist even though "check_deliverability" is true.

**Comment by JoshData** [comment]
I get a timeout when querying the DNS of that domain. The library errs on the side of caution with timeouts since they probably more often represent temporary failures.

I'm surprised by the timeout. The domain has a nameserver that is not responding to any queries (I think).

**Comment by JoshData** [comment]
I used `dig` on my desktop. When I try from a server, I get SERVFAIL as you do --- I think the nameserver is refusing connections. In any case, both of these conditions are treated the same by the library.

>  Optionally, is giving a "Timeout" error reasonable?

I'm not sure that in general it's a good idea. There are a lot of inputs that are valid but are not anyone's email address, and turning these cases into errors would probably mark valid addresses as invalid. Maybe with an option. But even then I'm not sure there's a big payoff unless there are a lot of unresponsive domains that are common spelling errors or something like that.

**Comment by Devunull** [comment]
That makes sense.


About time out cases. My use case is quite literally, handling many
misspellings so it'd be helpful to have for sure in my case.

Any kind of increased granulated control over error response would
be appreciated I think. Managing that with respect to using it in a simple
fashion may be hard.

Might be better to fork it in my case i think for the better granula
control (for cases like this).

**Comment by Devunull** [comment]
Maybe an optional param like `on_timeout=my_func` could work?

**Comment by nhairs-lumin** [comment]
From my experience you definitely don't want to equate SERVFAIL to the domain not existing. It is quite possible that there is a problem is the resolver that you were using. For example I have seen the default AWS EC2 resolver fail to resolve an entire TLD even though other resolvers (e.g. cloudflare) could.

In terms of adhoc testing of a domain, I'd reccomend also doing a `whois` lookup. It's sometimes possible to register a name with no / broken name servers. An example is if the name server records point to a name server that doesn't believe they are the name server (in other words, just because the name server is listed in the registry doesn't mean it's actually the name server).

If you are only concerned with email addresses on domains that could be registered (even if no longer registered), I'd consider parsing them using the Public Suffix List - although this doesn't account for TLDs / eTLDs that have ceased to exist (more likely for an eTLD than TLD). See my answer on [#111](https://github.com/JoshData/python-email-validator/issues/111#issuecomment-1807351210)

**Comment by JoshData** [comment]
:+1:
