### ISSUE TITLE
dnspython vulnerabilities

### ISSUE THREAD

**Issue by cgodley-tpx-land-reg** [JoshData/python-email-validator#136]
Hi there, 

dnspython below version 2.6.0 has the following vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2023-29483
additionally dnspython version 2.6.0 has this vulnerability: https://security.snyk.io/vuln/SNYK-PYTHON-DNSPYTHON-6241713

As such would it be possible to upgrade to version 2.6.1 in the dependencies?

**Comment by cgodley-tpx-land-reg** [comment]
My mistake, I see the latest version is already on 2.6.1. Apologies!

**Comment by JoshData** [comment]
I happened to have just done it as part of a general update this morning. However, the test_dependencies.txt file is only used in testing where DNS responses are mocked, so there was no relevant vulnerability for this package. And this package doesn't pin to specific versions of its dependencies for installation. So I'm not sure what the point of this issue was.
