### ISSUE TITLE
Set max email address length to 254?

### ISSUE THREAD

**Issue by sanjioh** [JoshData/python-email-validator#35]
Hi,

according to this verified erratum of RFC 3696:

https://www.rfc-editor.org/errata_search.php?rfc=3696&eid=1690

an email address should have a maximum of 254 characters.

I've noticed that `python-email-validator` does not enforce this limit: would you consider a PR implementing such check or it would be out of scope?

Thanks!

**Comment by JoshData** [comment]
Yes thanks!

**Comment by sanjioh** [comment]
Fixed in #36

**Comment by JoshData** [comment]
Per the discussion in the PR:

For the local part of the email address (before the @-sign), using the UTF-8 length makes sense to me. If the local part isn't internationalized, counting characters and UTF-8 octets are the same. If it is internationalized, the only way it will be transmitted is as UTF-8 to SMTPUTF8-capable MTAs. And given the link you gave suggesting octets is what counts, and since counting octets is more restrictive (and so errs on the side of compatibility with MTAs), counting UTF-8 octets makes sense.

For the domain name, if the local part isn't internationalized, then one can't assume that the MTAs on the path to the destination will all support SMTPUTF8 (in fact, the caller might know that their own MTA doesn't), and so the domain name will be encoded in IDNA (not UTF-8). Counting the characters in the IDNA encoding rather than the UTF-8 encoding is probably right in this case. (IDNA is single-byte, so characters and octets are the same.)

If the local part _is_ internationalized, and if one assumes that all of the MTAs on the path to the destination support SMTPUTF8 (otherwise it won't be deliverable), counting the UTF-8 length of the domain part too makes sense in this case since the email address will have to be transmitted in UTF-8. But since the IDNA form of the domain name is equivalent to the internationalized form, it's plausible that some MTAs might re-write the domain name using IDNA, and since the IDNA form is always longer than the UTF-8 form (I think), a strict check _might_ count the domain name part of the length using IDNA octets to be sure.

It's also plausible to me because MTA implementations are extremely variable that there are deliverable (at least by popular MTAs) addresses whose UTF-8 length exceeds the limit but whose character count doesn't (i.e. the MTA implementations actually are more lax and count characters), and so it might make sense to be lax and count characters always.

In addition, Unicode NFC normalization is supposed to be applied to local parts, and the normalized form may have more or fewer characters, so the length check ought to be on the normalized form, but this might be either more lax or more strict depending on whether the given email address increases or decreases in length after normalization.

**Comment by JoshData** [comment]
I added some length checks per this discussion. Thanks!
